### ISSUE TITLE
Items not picked, Shenk not done (stands in params = 1)

### ISSUE THREAD

**Issue by aGeftw** [aeon0/botty#87] opened 2021-11-23 09:56 UTC
**Botty Version**
0.3.0

**Describe the bug**
after kill, "alt" would not be pushed and items analysed. (Color-Settings are done)

**To Reproduce**
3. etc.

**Expected behavior**

**Screenshots / Video**
If applicable, add screenshots or even better a short video of the error happening to help explain your problem. Botty often automatically makes screenshots when something goes wrong. Add these also.

**Logs**
2021-11-23 10:48:51,440] INFO       Run Pindle
Exception in thread Thread-4:
Traceback (most recent call last):
  File "C:\Users\blubb\AppData\Local\Temp\ONEFIL~2\threading.py", line 932, in _bootstrap_inner
  File "C:\Users\blubb\AppData\Local\Temp\ONEFIL~2\threading.py", line 870, in run
  File "C:\Users\blubb\AppData\Local\Temp\ONEFIL~2\bot.py", line 270, in doit
  File "C:\Users\blubb\AppData\Local\Temp\ONEFIL~2\char\hammerdin.py", line 65, in kill_pindle
  File "C:\Users\blubb\AppData\Local\Temp\ONEFIL~2\char\hammerdin.py", line 51, in _do_redemption
  File "C:\Users\blubb\AppData\Local\Temp\ONEFIL~2\keyboard\__init__.py", line 379, in send
  File "C:\Users\blubb\AppData\Local\Temp\ONEFIL~2\keyboard\__init__.py", line 358, in parse_hotkey
  File "C:\Users\blubb\AppData\Local\Temp\ONEFIL~2\keyboard\__init__.py", line 358, in <genexpr>
  File "C:\Users\blubb\AppData\Local\Temp\ONEFIL~2\keyboard\__init__.py", line 309, in key_to_scan_codes
  File "C:\Users\blubb\AppData\Local\Temp\ONEFIL~2\keyboard\_canonical_names.py", line 1239, in normalize_name
ValueError: Can only normalize non-empty string names. Unexpected ''
[2021-11-23 10:49:25,844] INFO       Run Eldritch
Exception in thread Thread-7:
Traceback (most recent call last):
  File "C:\Users\blubb\AppData\Local\Temp\ONEFIL~2\threading.py", line 932, in _bootstrap_inner
  File "C:\Users\blubb\AppData\Local\Temp\ONEFIL~2\threading.py", line 870, in run
  File "C:\Users\blubb\AppData\Local\Temp\ONEFIL~2\bot.py", line 309, in doit
  File "C:\Users\blubb\AppData\Local\Temp\ONEFIL~2\char\hammerdin.py", line 76, in kill_eldritch
  File "C:\Users\blubb\AppData\Local\Temp\ONEFIL~2\char\hammerdin.py", line 51, in _do_redemption
  File "C:\Users\blubb\AppData\Local\Temp\ONEFIL~2\keyboard\__init__.py", line 379, in send
  File "C:\Users\blubb\AppData\Local\Temp\ONEFIL~2\keyboard\__init__.py", line 358, in parse_hotkey
  File "C:\Users\blubb\AppData\Local\Temp\ONEFIL~2\keyboard\__init__.py", line 358, in <genexpr>
  File "C:\Users\blubb\AppData\Local\Temp\ONEFIL~2\keyboard\__init__.py", line 309, in key_to_scan_codes
  File "C:\Users\blubb\AppData\Local\Temp\ONEFIL~2\keyboard\_canonical_names.py", line 1239, in normalize_name
ValueError: Can only normalize non-empty string names. Unexpected ''
[2021-11-23 10:49:48,676] INFO       End game. Elapsed time: 76.45s

**Additional info**
i am using shadow.tech as cloud gaming computer. so my keyboard is connected through cloud session.

**Comment by aeon0** [comment] 2021-11-23 14:12
2 things. 

1) Current version it says redemption is optional. It really is not because of a bug. You must use it.
2) If alt pressing issues as eld it often is caused by not setting item pickup to hold but to toggle instead.

**Comment by aGeftw** [comment] 2021-11-24 12:59
redemption used, and now the pick up items, too. 

now i get only a stuck error on teleport to shenk

**Comment by aeon0** [comment] 2021-11-25 05:23
Sounds good, different issue. Closing

**Closed by aeon0** 2021-11-25 05:23 UTC
