### ISSUE TITLE
 item_cropper failed for slot_pos

### ISSUE THREAD

**Issue by SpheresOfMadness** [aeon0/botty#705] opened 2022-04-15 07:54 UTC
When mousing over items in inventory botty gives me this error message

[0.7.2 2022-04-15 03:44:54,828] DEBUG      Inspecting inventory items
[0.7.2 2022-04-15 03:44:55,903] ERROR      item_cropper failed for slot_pos: (885, 367)
[0.7.2 2022-04-15 03:44:56,519] ERROR      item_cropper failed for slot_pos: (885, 405)
[0.7.2 2022-04-15 03:44:57,168] ERROR      item_cropper failed for slot_pos: (885, 443)
[0.7.2 2022-04-15 03:44:57,765] ERROR      item_cropper failed for slot_pos: (923, 367)
[0.7.2 2022-04-15 03:44:58,347] ERROR      item_cropper failed for slot_pos: (923, 405)
[0.7.2 2022-04-15 03:44:58,944] ERROR      item_cropper failed for slot_pos: (923, 443)
[0.7.2 2022-04-15 03:44:59,541] ERROR      item_cropper failed for slot_pos: (961, 367)

this also stops botty from stashing the item.

**Comment by SpheresOfMadness** [comment] 2022-04-15 07:56
![failed_item_box_20220415_035004](https://user-images.githubusercontent.com/103730422/163542575-c93f51cb-c359-4fb6-a184-df8ae172f3e8.png)
![failed_item_box_20220415_035005](https://user-images.githubusercontent.com/103730422/163542581-dadc02ab-32a5-411d-a032-7233df227f07.png)
![failed_item_box_20220415_035121](https://user-images.githubusercontent.com/103730422/163542585-3fa8d660-7c9d-47ba-8286-f10293630cd7.png)
![failed_item_box_20220415_035122](https://user-images.githubusercontent.com/103730422/163542587-ec5105a8-cdb9-49b4-a263-7cefa603e9bd.png)
![failed_item_box_20220415_035123](https://user-images.githubusercontent.com/103730422/163542590-bd8e00bc-1a90-4850-a89a-a02218263dc6.png)
![failed_item_box_20220415_035124](https://user-images.githubusercontent.com/103730422/163542592-4b48dc32-04f7-432b-8cb9-be9d7aabea45.png)
![failed_item_box_20220415_035125](https://user-images.githubusercontent.com/103730422/163542594-2f2d30ef-11b5-4dc1-8674-a63f1b932741.png)
![failed_item_box_20220415_034455](https://user-images.githubusercontent.com/103730422/163542595-5942b047-0c90-4b07-92ae-64edbc2d5291.png)
![failed_item_box_20220415_034456](https://user-images.githubusercontent.com/103730422/163542597-70407ae8-2faa-4b4a-8be0-810e242ed989.png)
![failed_item_box_20220415_034457](https://user-images.githubusercontent.com/103730422/163542602-061d213a-7e92-477b-80b8-fff9710ff871.png)
![failed_item_box_20220415_034458](https://user-images.githubusercontent.com/103730422/163542605-40b22ac7-e173-4ea0-b753-a0461714d79a.png)
![failed_item_box_20220415_034459](https://user-images.githubusercontent.com/103730422/163542607-82e5ed6a-2598-4a49-9318-1ec28290d3eb.png)
![failed_item_box_20220415_034722](https://user-images.githubusercontent.com/103730422/163542610-1289c219-c06a-426c-97ee-cd193548c8e2.png)
![failed_item_box_20220415_034723](https://user-images.githubusercontent.com/103730422/163542613-dd4075a0-a8c2-49ea-9031-5c140f842fde.png)
![failed_item_box_20220415_034724](https://user-images.githubusercontent.com/103730422/163542617-ec7848da-c273-4f23-8449-763b0900a453.png)
![failed_item_box_20220415_034725](https://user-images.githubusercontent.com/103730422/163542620-6c4e9e7c-cdbf-4911-9e49-2c72ef1568c3.png)
![failed_item_box_20220415_034726](https://user-images.githubusercontent.com/103730422/163542622-820b3632-ce57-4e5f-8bef-8e779ec1bfa3.png)
![failed_item_box_20220415_034841](https://user-images.githubusercontent.com/103730422/163542627-f7da8fac-70fc-4ed4-ac57-cac5367038fd.png)
![failed_item_box_20220415_034842](https://user-images.githubusercontent.com/103730422/163542629-38dc98e0-3197-41f7-8da8-9b228aa6e874.png)
![failed_item_box_20220415_034843](https://user-images.githubusercontent.com/103730422/163542631-ace2f22a-7b1f-412e-add9-b93e6a18a659.png)
![failed_item_box_20220415_034844](https://user-images.githubusercontent.com/103730422/163542633-19685887-183c-47a3-977e-e90ef1b6cca9.png)
![failed_item_box_20220415_034845](https://user-images.githubusercontent.com/103730422/163542634-f5909b22-1de7-4dfa-b962-81caa519aae4.png)
![failed_item_box_20220415_035002](https://user-images.githubusercontent.com/103730422/163542636-5aae9616-91b4-4bc1-9f05-67b0cf6b672b.png)
![failed_item_box_20220415_035003](https://user-images.githubusercontent.com/103730422/163542638-a9d21c2f-e120-4f88-9caf-1a3c09f05981.png)

**Comment by muchachos11** [comment] 2022-04-15 09:11
Hi, I got the same problem. It dosen´t identify rares or stash white/grey items. It does however stash runes.

**Comment by maszicptn** [comment] 2022-04-15 10:22
Hi, same here. Also my hammerdin (no enigma) can't do travincal since yesterday as he is struggling to find the way to the high council. 
Not sure if it relates to the recent D2R release, but these were working for me before

**Comment by krisvuk** [comment] 2022-04-15 17:09
Same issue - bot is basically dead in the water as the inventory fills. Looks like it happens to slots in the upper area of the inventory, or when an item is over those areas.

**Comment by GloriousHeritage** [comment] 2022-04-15 17:37
Same issue here. It appeared after the patch.

**Comment by mgleed** [comment] 2022-04-15 17:44
Bug is fixed on master branch. You can either run from source or wait on a release to fix.

**Comment by mgleed** [comment] 2022-04-15 17:45
> Hi, same here. Also my hammerdin (no enigma) can't do travincal since yesterday as he is struggling to find the way to the high council. Not sure if it relates to the recent D2R release, but these were working for me before

Trav pathing issue is known and is related to graphics changes in Trav. Fix is in the works

**Comment by maszicptn** [comment] 2022-04-15 17:46
thank you

**Comment by Tonkooo** [comment] 2022-04-18 12:48
#mgleed i am not aware how to run from the master branch, so when can we expect the fixed release?

**Comment by xdb1984** [comment] 2022-04-21 05:34
> Bug is fixed on master branch. You can either run from source or wait on a release to fix.

        for key in self.routes_order:
            self.routes[key] = True

run from source and found routes config is all true

**Comment by ek6ou** [comment] 2022-04-21 21:55
The issue is still present, even with the new release 0.7.3.
It happens with all the slots in the first 5 columns (I haven't tried with more than 5).
And it is present in all areas, not only trav

**Comment by Redman920** [comment] 2022-04-21 22:04
> The issue is still present, even with the new release 0.7.3.
> It happens with all the slots in the first 5 columns (I haven't tried with more than 5).
> And it is present in all areas, not only trav

This is likely because you have old files on your computer, delete everything body related and redownload. This issue has been corrected.

**Comment by ek6ou** [comment] 2022-04-22 14:21
> > The issue is still present, even with the new release 0.7.3.
> > It happens with all the slots in the first 5 columns (I haven't tried with more than 5).
> > And it is present in all areas, not only trav
> 
> This is likely because you have old files on your computer, delete everything botty related and redownload. This issue has been corrected.

You were right, I forgot to apply the "Adjust D2R settings".

**Comment by Redman920** [comment] 2022-04-22 14:41
Right on!!

**Closed** 2022-06-06 19:32 UTC
