### ISSUE TITLE
When the robot runs, it goes deep into Pindle Skin and dies

### ISSUE THREAD

**Issue by wedqdas** [aeon0/botty#578] opened 2022-02-22 15:17 UTC
When the robot runs, it goes deep into Pindle Skin and dies. I set the graphic by pressing f9, and I set the stand still and force move exactly, but I'm attaching a screenshot. I wonder if anyone knows how to solve this error. Crying.
bot0.6.4 
![boterror](https://user-images.githubusercontent.com/99885505/155162504-a4e595bc-8909-4e3d-b2be-7cdb1ce45b4e.jpg)

**Comment by wedqdas** [comment] 2022-02-22 15:18
I can't find my way or red portal.

**Comment by Kellen-Stuart** [comment] 2022-02-24 01:58
I have too noticed this issue. Occasionally botty will teleport directly into the middle of Pindle, nearly die, then Save & Exit. Not sure if it's a graphical offset issue or what is causing it.

**Comment by offerduo** [comment] 2022-02-24 06:00
> I have too noticed this issue. Occasionally botty will teleport directly into the middle of Pindle, nearly die, then Save & Exit. Not sure if it's a graphical offset issue or what is causing it.

It happened to me occasionally as well. I think the extra tp might be because bot think the tp was cancelled or not done properly.
I need to fine tune the 'casting_frames'.
And there's another time I disconnected the power cord and my laptop is not bright enough.
I think this will affect the pattern recognition.

**Comment by Kellen-Stuart** [comment] 2022-02-27 19:22
I'm going to try to debug this today. It has been happening more frequently and causes deaths. I'll report back on my findings (if I find anything).

**Comment by doschhar** [comment] 2022-02-28 09:58
Guess there should be location crosscheck after teleport - so tele > crosscheck location > tele ...
at least for the last tele in the pindle hall (like reach final waypoint confirmed, stop tele)

**Comment by doschhar** [comment] 2022-02-28 09:59
> I need to fine tune the 'casting_frames'.

its not only  'casting_frames' mine would be 8 I use 14 and still it happens that bot teles by the last waypoint right into the group

**Comment by D2RLegit** [comment] 2022-03-01 13:56
Prebuff hotkeys not setup correctly.

**Comment by doschhar** [comment] 2022-03-01 14:12
> Prebuff hotkeys not setup correctly.

they are set correctly.

problems has been reported several times also in discord that bot says "teleport cancel detected. try same teleport again" and teleports right into pindle because of wrong cancel detection. cast_frames set with lots of safety to real cast speed.

> I'm going to try to debug this today. It has been happening more frequently and causes deaths. I'll report back on my findings (if I find anything).

correct.

**Comment by mgleed** [comment] 2022-03-06 01:44
Closing for now. If you notice this again, please use the issues template!

**Closed by mgleed** 2022-03-06 01:44 UTC
